In [7]:
import pandas as pd
import numpy as np
from collections import Counter

df = pd.read_csv('AAPL.csv')

#choosing close col
close_prices = df['Close']

mean = np.mean(close_prices)
median = np.median(close_prices)
mode_data = Counter(close_prices)
mode = mode_data.most_common(1)[0][0]

std_dev = np.std(close_prices)

print('Mean: ',mean)
print('Median: ',median)
print('Mode: ',mode)
print('Standard Deviation: ',std_dev)


Mean:  21.317730618422253
Median:  0.4296391606330871
Mode:  0.0852759033441543
Standard Deviation:  45.18749651974093


In [6]:
import numpy as np

# Assuming df['likes'], df['comments'], df['shares'], and df['views'] are numerical arrays
likes = df['likes'].to_numpy()
comments = df['comments'].to_numpy()
shares = df['shares'].to_numpy()
views = df['views'].to_numpy()

# Basic NumPy Operations
# Indexing
first_like = likes[0]

# Slicing
likes_slice = likes[10:20]

# Splitting
likes_split = np.array_split(likes, 5)

# Iterating
for like in likes:
    print(like)

# Advanced NumPy Operations
# Filtering (likes > 100)
filtered_likes = likes[likes > 100]

# Sorting
sorted_likes = np.sort(likes)

# Combining (likes and comments)
combined = np.concatenate((likes, comments))

# Reshaping (if you want to reshape to a 2D array)
reshaped_likes = likes.reshape(-1, 1)  # reshapes to a column vector


Mean:  21.302670824531234
Median:  0.430761270301473
Mode:  0.0525434724986553
Standard Deviation:  45.14661511687005


In [25]:
import numpy as np

import numpy as np

# Load TikTok video performance data using genfromtxt with specific dtype
data = np.genfromtxt('tiktok_performance.csv', delimiter=',', skip_header=1, 
                     dtype=[('Likes', 'i4'), ('Comments', 'i4'), ('Shares', 'i4'), ('Views', 'i4')],
                     filling_values=0,  # Fill missing values with 0
                     encoding='utf-8')

# Extracting specific columns
likes = data['Likes']
comments = data['Comments']

# Continue with your NumPy operations...


# Basic NumPy Operations
# Indexing
first_like = likes[0]
print(first_like)
# Slicing
likes_slice = likes[10:20]
print(likes_slice)
# Splitting
likes_split = np.array_split(likes, 5)
print(likes_split)
# Iterating
for like in likes:
    print(like)

# Advanced NumPy Operations
# Filtering (likes > 100)
filtered_likes = likes[likes > 100]
print(filtered_likes)
# Sorting
sorted_likes = np.sort(likes)
print(sorted_likes)
# Combining (likes and comments)
combined = np.concatenate((likes, comments))
print(combined)
# Reshaping (if you want to reshape to a 2D array)
reshaped_likes = likes.reshape(-1, 1)  # reshapes to a column vector
print(reshaped_likes)


101
[]
[array([101]), array([102]), array([103]), array([104]), array([105])]
101
102
103
104
105
[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105   1   2   3   4   5]
[[101]
 [102]
 [103]
 [104]
 [105]]


In [27]:
import pandas as pd

# Basic Pandas Operations
# Indexing
first_row = df.iloc[0]

# Slicing
sliced_df = df.iloc[10:20]

# Iterating (iterating over rows)
for index, row in df.iterrows():
    print(f"Video ID: {row['Video_ID']}, Likes: {row['Likes']}")

# Advanced Pandas Operations
# Filtering (videos with more than 100 likes)
filtered_df = df[df['likes'] > 100]

# Sorting (sort by views)
sorted_df = df.sort_values(by='views', ascending=False)

# Reshaping (pivoting)
pivot_df = df.pivot_table(values='engagement_rate', index='category', aggfunc='mean')

print("Filtered DataFrame:\n", filtered_df.head())
print("Sorted DataFrame:\n", sorted_df.head())
print("Pivot Table:\n", pivot_df)


KeyError: 'Video_ID'